import { z } from "zod";
import {
  myActivity,
  myActivityQuery,
  publicSearchQuery,
  publicSearchResult,
} from "./resources.js";
import {
  adminSubject,
  anchorBatchStatus,
  attestationDispute,
  bindWalletRequest,
  auditEvent,
  authorityEntry,
  jurisdictionProfileView,
  authorityRegisterRequest,
  authorityStateRequest,
  authorityUpdateRequest,
  authorityVersionEntry,
  connectionConfigureRequest,
  offeringGateStatus,
  sourceConnectionEntry,
  evidenceStaleSignal,
  resolveStaleSignalRequest,
  secondReviewRequest,
  sourceCollectRequest,
  sourceCollectResult,
  createAttestationRequest,
  objectUpload,
  scannerStatus,
  uploadDownloadLink,
  createGateDecisionRequest,
  createProjectRequest,
  createRoleGrantRequest,
  createNotificationSinkRequest,
  createSubjectRequest,
  decideRoleGrantRequest,
  disableWalletRequest,
  createProposalRequest,
  castVoteRequest,
  disputeAttestationRequest,
  governanceProposal,
  transitionProposalRequest,
  claim,
  gateDecision,
  inclusionProofResponse,
  projectSummary,
  projectLifecycle,
  projectLifecycleTransitionRequest,
  publicProjection,
  publicCursorQuery,
  publicDisclosureList,
  publicProposalDetail,
  publicProposalList,
  publicRegistryList,
  publicRegistryListQuery,
  readinessAssessment,
  registryEntryVersion,
  registryEntrySummary,
  myWork,
  notification,
  notificationSink,
  updateNotificationSinkRequest,
  outboxBacklog,
  resolveDisputeRequest,
  roleGrantRequest,
  sourceReceipt,
  transitionCaseRequest,
  verificationAttestation,
  verificationCaseSummary,
} from "./resources.js";
import {
  sessionResponse,
  signatureRequestResponse,
  siweNonceRequest,
  siweNonceResponse,
  siweVerifyRequest,
  submitSignatureRequest,
} from "./auth.js";

/**
 * Route 정의 — spec 07 §7.2.
 *
 * 여기 없는 경로는 존재하지 않는다. 특히 readiness 결과를 수정하는 경로가
 * 없는 것이 통제다(REQ-DAPP-017) — 권한으로 막는 것이 아니라 만들지 않는다.
 */

export interface RouteDefinition {
  readonly method: "get" | "post" | "patch" | "delete";
  readonly path: string;
  readonly summary: string;
  readonly operationId: string;
  /** 무인증 공개 route인가(§7.1). */
  readonly public: boolean;
  /** mutation이면 Idempotency-Key가 필수다. */
  readonly mutation: boolean;
  /** versioned resource mutation이면 If-Match가 필수다. */
  readonly requiresIfMatch: boolean;
  readonly action: string | null;
  /**
   * 이 route가 실제로 구현됐는가.
   *
   * 계약은 목표 API를 담고 구현은 그것을 따라간다. 두 상태를 구분하지 않으면
   * "계약에 있으니 있겠지"라고 믿게 되고, 반대로 구현만 있고 계약에 없는
   * route가 조용히 늘어난다. `apps/api`의 parity 테스트가 이 플래그를 기준으로
   * 양방향 드리프트를 잡는다.
   */
  readonly implemented: boolean;
  /** 구현 예정 release. `implemented: false`일 때만 의미가 있다. */
  readonly plannedRelease?: "R1" | "R2" | "R3" | "R6";
  readonly requestSchema?: z.ZodTypeAny;
  /**
   * query string 계약.
   *
   * 페이지네이션·정렬·필터는 body가 없는 GET에 붙으므로 `requestSchema`로는
   * 표현되지 않는다. 계약에 두지 않으면 OpenAPI에도 나타나지 않고, 그러면
   * 클라이언트가 무엇을 보낼 수 있는지 코드를 읽어야 안다.
   */
  readonly querySchema?: z.ZodTypeAny;
  readonly responseSchema: z.ZodTypeAny;
}

export const ROUTES: readonly RouteDefinition[] = [
  // --- 인증 ---------------------------------------------------------------
  {
    method: "post",
    path: "/api/v1/auth/siwe/nonce",
    summary: "SIWE 로그인 challenge nonce 발급",
    operationId: "createSiweNonce",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    requestSchema: siweNonceRequest,
    responseSchema: siweNonceResponse,
  },
  {
    method: "post",
    path: "/api/v1/auth/siwe/verify",
    summary: "SIWE 서명 검증 후 세션 발급",
    operationId: "verifySiweSignature",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    requestSchema: siweVerifyRequest,
    responseSchema: sessionResponse,
  },
  {
    method: "post",
    path: "/api/v1/auth/logout",
    summary: "세션 토큰 폐기 — 즉시 무효가 된다",
    operationId: "logout",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: sessionResponse,
  },
  {
    method: "get",
    path: "/api/v1/auth/session",
    summary: "현재 identity·role·assurance level 조회",
    operationId: "getSession",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: sessionResponse,
  },

  // --- Project ------------------------------------------------------------
  {
    method: "post",
    path: "/api/v1/projects",
    summary: "프로젝트 등록",
    operationId: "createProject",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "project.create",
    implemented: true,
    requestSchema: createProjectRequest,
    responseSchema: projectSummary,
  },
  {
    method: "get",
    path: "/api/v1/projects",
    summary: "현재 tenant의 프로젝트 목록",
    operationId: "listProjects",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: projectSummary.array(),
  },
  {
    method: "get",
    path: "/api/v1/projects/{projectId}",
    summary: "프로젝트 조회",
    operationId: "getProject",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: projectSummary,
  },

  // --- Evidence -----------------------------------------------------------
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/source-receipts",
    summary: "Source Receipt 목록",
    operationId: "listSourceReceipts",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: sourceReceipt.array(),
  },
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/claims",
    summary: "claim 목록",
    operationId: "listClaims",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: claim.array(),
  },

  {
    method: "post",
    path: "/api/v1/projects/{projectId}/source-receipts",
    summary: "Source Receipt 등록 — API·문서·수동 확인이 같은 envelope를 쓴다",
    operationId: "createSourceReceipt",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    responseSchema: sourceReceipt,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/claims",
    summary: "claim 등록 — grade는 도메인 규칙이 계산한다",
    operationId: "createClaim",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "claim.curate",
    implemented: true,
    responseSchema: claim,
  },
  {
    method: "post",
    path: "/api/v1/claims/{claimId}/conflicts",
    summary: "claim conflict 기록 — grade를 즉시 재계산한다",
    operationId: "createClaimConflict",
    public: false,
    mutation: true,
    // grade 재계산이 claim version을 올린다. 동시 기록에서 한쪽 판단이 조용히
    // 덮이지 않게 어느 버전을 보고 기록하는지 밝혀야 한다.
    requiresIfMatch: true,
    action: "claim.curate",
    implemented: true,
    responseSchema: claim,
  },

  // --- 업로드 --------------------------------------------------------------
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/uploads",
    summary: "업로드 목록 — 검사기가 살아 있는지도 함께 말한다",
    operationId: "listUploads",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    // `items`와 `scanner`를 함께 낸다. 목록만 보면 "대기"와 "검사할 사람이
    // 없음"이 같아 보인다.
    responseSchema: z.object({ items: objectUpload.array(), scanner: scannerStatus }),
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/uploads",
    summary: "파일 업로드 — quarantine으로 먼저 들어간다",
    operationId: "createUpload",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    responseSchema: objectUpload,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/uploads/stream",
    summary: "파일 업로드 (multipart) — 대용량을 메모리에 올리지 않는다",
    operationId: "createUploadStream",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    responseSchema: objectUpload,
  },
  {
    method: "post",
    path: "/api/v1/uploads/{uploadId}/scan-result",
    summary: "검사 결과 기록 — 검사 서비스가 호출한다. 감염 판정은 되돌릴 수 없다",
    operationId: "recordScanResult",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    // 올린 사람이 자기 파일을 통과시킬 수 없게 별도 action을 쓴다.
    action: "upload.scan_result",
    implemented: true,
    responseSchema: objectUpload,
  },
  {
    method: "post",
    path: "/api/v1/uploads/{uploadId}/promote",
    summary: "evidence 승격 — 검사를 통과한 것만 간다",
    operationId: "promoteUpload",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "source.upload",
    implemented: true,
    responseSchema: objectUpload,
  },
  {
    method: "post",
    path: "/api/v1/uploads/{uploadId}/download-link",
    summary: "단기 다운로드 링크 — 영구 URL을 만들지 않는다",
    operationId: "createUploadDownloadLink",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    responseSchema: uploadDownloadLink,
  },

  // --- Verification -------------------------------------------------------
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/verification-cases",
    summary: "검토 case 목록 — 배정된 검토자가 자기 case를 찾는 경로",
    operationId: "listVerificationCases",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: verificationCaseSummary.array(),
  },
  {
    method: "post",
    path: "/api/v1/verification-cases/{caseId}/transitions",
    summary: "검토 case 상태 전이 — 보완 요청·반려·취소를 기록한다",
    operationId: "transitionVerificationCase",
    public: false,
    mutation: true,
    // 상태는 case의 version이 아니라 state 자체가 바뀐다. 같은 case에 두 사람이
    // 동시에 다른 결정을 기록하면 하나가 조용히 사라진다.
    requiresIfMatch: true,
    action: "claim.curate",
    implemented: true,
    requestSchema: transitionCaseRequest,
    responseSchema: verificationCaseSummary,
  },
  {
    method: "post",
    path: "/api/v1/attestations/{attestationId}/disputes",
    summary: "서명된 attestation에 이의 제기 — 서명을 지우지 않고 상태를 추가한다",
    operationId: "disputeAttestation",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.dispute",
    implemented: true,
    requestSchema: disputeAttestationRequest,
    responseSchema: verificationAttestation,
  },
  {
    method: "get",
    path: "/api/v1/attestations/{attestationId}/disputes",
    summary: "이의 목록 — 해소된 것도 함께 보인다",
    operationId: "listDisputes",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: attestationDispute.array(),
  },
  {
    method: "post",
    path: "/api/v1/disputes/{disputeId}/resolution",
    summary: "이의 해소 — 기록을 지우지 않고 결과를 덧붙인다",
    operationId: "resolveDispute",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.dispute",
    implemented: true,
    requestSchema: resolveDisputeRequest,
    responseSchema: attestationDispute,
  },
  {
    method: "post",
    path: "/api/v1/verification-cases/{caseId}/attestations",
    summary: "attestation 초안 생성 (서명 전)",
    operationId: "createAttestation",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.sign",
    implemented: true,
    requestSchema: createAttestationRequest,
    responseSchema: verificationAttestation,
  },
  {
    method: "post",
    path: "/api/v1/attestations/{attestationId}/signature-requests",
    summary: "EIP-712 서명 요청 생성 — 서버는 대리 서명하지 않는다",
    operationId: "createSignatureRequest",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.sign",
    implemented: true,
    responseSchema: signatureRequestResponse,
  },
  {
    method: "post",
    path: "/api/v1/attestations/{attestationId}/signatures",
    summary: "사용자 key로 만든 서명 제출 — 서버는 재계산·검증만 한다",
    operationId: "submitAttestationSignature",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.sign",
    implemented: true,
    requestSchema: submitSignatureRequest,
    responseSchema: verificationAttestation,
  },

  {
    method: "post",
    path: "/api/v1/verification-cases",
    summary: "Verification Case 생성 — evidence snapshot을 고정한다",
    operationId: "createVerificationCase",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "claim.curate",
    implemented: true,
    responseSchema: verificationAttestation,
  },

  // --- Readiness / Decision -----------------------------------------------
  //
  // readiness를 PATCH하는 경로는 존재하지 않는다. 재계산만 가능하다(§7.2).
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/readiness-assessments",
    summary: "readiness 재계산 — 기존 결과를 수정하지 않고 새 assessment를 만든다",
    operationId: "createReadinessAssessment",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "readiness.recompute",
    implemented: true,
    responseSchema: readinessAssessment,
  },
  {
    method: "get",
    path: "/api/v1/readiness-assessments/{assessmentId}",
    summary: "readiness 조회",
    operationId: "getReadinessAssessment",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: readinessAssessment,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/gate-decisions",
    summary: "사람의 gate 결정 기록",
    operationId: "createGateDecision",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "gate.decide",
    implemented: true,
    requestSchema: createGateDecisionRequest,
    responseSchema: gateDecision,
  },

  // --- Registry -----------------------------------------------------------
  {
    method: "post",
    path: "/api/v1/registry-entries",
    summary: "공개 승인된 version 게시 — allowlist 밖 필드를 거절한다",
    operationId: "publishRegistryVersion",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "registry.publish",
    implemented: true,
    responseSchema: registryEntryVersion,
  },
  {
    method: "post",
    path: "/api/v1/registry-entries/{entryId}/revoke",
    summary: "게시 철회 — 기존 version을 삭제하지 않고 새 상태를 추가한다",
    operationId: "revokeRegistryVersion",
    public: false,
    mutation: true,
    // 조회 이후 새 version이 게시됐을 수 있다. 의도한 version을 밝힌다.
    requiresIfMatch: true,
    action: "registry.revoke",
    implemented: true,
    responseSchema: registryEntryVersion,
  },

  {
    method: "get",
    path: "/api/v1/anchor-batches",
    summary: "anchor batch 체인 상태 — included와 confirmed를 구분해 보여준다",
    operationId: "listAnchorBatches",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: anchorBatchStatus.array(),
  },
  {
    method: "post",
    path: "/api/v1/anchor-batches",
    summary: "Merkle batch 생성 — 게시된 version만 포함한다",
    operationId: "createAnchorBatch",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "anchor.submit",
    implemented: true,
    responseSchema: registryEntryVersion,
  },

  {
    method: "post",
    path: "/api/v1/anchor-batches/{batchId}/resubmit",
    summary: "멈춘 anchor batch 재제출 — 자동이 아니라 사람이 판단한다",
    operationId: "resubmitAnchorBatch",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "anchor.submit",
    implemented: true,
    responseSchema: anchorBatchStatus,
  },

  {
    method: "post",
    path: "/api/v1/source-receipts/{receiptId}/second-review",
    summary: "수동 확인의 두 번째 검토 — 처음 확인한 사람은 할 수 없다",
    operationId: "recordSecondReview",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.collect",
    implemented: true,
    requestSchema: secondReviewRequest,
    responseSchema: sourceReceipt,
  },

  {
    method: "get",
    path: "/api/v1/projects/{projectId}/stale-signals",
    summary: "근거가 흔들린 산출물 — 열린 신호와 처리된 신호를 함께 본다",
    operationId: "listStaleSignals",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: evidenceStaleSignal.array(),
  },
  {
    method: "post",
    path: "/api/v1/stale-signals/{signalId}/resolve",
    summary: "신호 종결 — 공개 기록을 내리는 판정은 자동화하지 않는다",
    operationId: "resolveStaleSignal",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "registry.revoke",
    implemented: true,
    requestSchema: resolveStaleSignalRequest,
    responseSchema: evidenceStaleSignal,
  },

  // --- Asset/Offering gate (R6, OD-07) --------------------------------------
  //
  // 거래 route가 없다. 조건 판정만 있다 — 미승인 규제 기능은 flag 뒤에 있어도
  // 코드·보안·운영 책임과 오활성화 위험을 만든다.
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/lifecycle",
    summary: "lifecycle 상태와 지나온 경로 — 멈췄다 돌아온 것과 멈춘 적 없는 것은 다르다",
    operationId: "getProjectLifecycle",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "project.read",
    implemented: true,
    responseSchema: projectLifecycle,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/lifecycle-transitions",
    summary: "lifecycle 전이 — suspend는 1인, 복귀는 멈춘 사람이 못 한다",
    operationId: "transitionProjectLifecycle",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    // 실제 판정은 두 action으로 갈린다. 계약에는 더 넓은 쪽을 적고 route가
    // `toState`를 보고 고른다 — 04 §4.3의 비대칭이 여기 있다.
    action: "project.lifecycle.advance",
    implemented: true,
    requestSchema: projectLifecycleTransitionRequest,
    responseSchema: projectLifecycle,
  },
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/offering-gate",
    summary: "자산·청약 활성화 조건 — 남은 것과 담당을 반환한다",
    operationId: "getOfferingGate",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: offeringGateStatus,
  },

  // --- Authority Registry (R5) ---------------------------------------------
  {
    method: "get",
    path: "/api/v1/authorities",
    summary: "Authority 목록 — 확인하지 않는 것과 연동 상태를 함께 반환한다",
    operationId: "listAuthorities",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: authorityEntry.array(),
  },
  // 등록과 승인이 다른 action이다 — 02 §2.8은 운영자 단독 `accepted` 전환을
  // 금지한다. 같은 route에 넣으면 그 분리를 권한으로 표현할 수 없다.
  {
    method: "post",
    path: "/api/v1/authorities",
    summary: "Authority 후보 등록 — 항상 proposed에서 시작한다",
    operationId: "registerAuthority",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "authority.register",
    implemented: true,
    requestSchema: authorityRegisterRequest,
    responseSchema: authorityEntry,
  },
  {
    method: "patch",
    path: "/api/v1/authorities/{authorityId}",
    summary: "Authority 갱신 — 변경마다 이력이 남는다",
    operationId: "updateAuthority",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "authority.register",
    implemented: true,
    requestSchema: authorityUpdateRequest,
    responseSchema: authorityEntry,
  },
  {
    method: "post",
    path: "/api/v1/authorities/{authorityId}/state",
    summary: "Authority 상태 전환 — 등록한 사람은 승인할 수 없다",
    operationId: "decideAuthorityState",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "authority.review",
    implemented: true,
    requestSchema: authorityStateRequest,
    responseSchema: authorityEntry,
  },
  {
    method: "get",
    path: "/api/v1/authorities/{authorityId}/versions",
    summary: "Authority 이력 — 그때 무엇을 확인해 준다고 했는지",
    operationId: "listAuthorityVersions",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: authorityVersionEntry.array(),
  },
  {
    method: "get",
    path: "/api/v1/authorities/{authorityId}/connections",
    summary: "연동 목록 — 자격증명 값은 반환하지 않는다",
    operationId: "listSourceConnections",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: sourceConnectionEntry.array(),
  },
  {
    method: "post",
    path: "/api/v1/authorities/{authorityId}/connections",
    summary: "연동 구성 — 승인되지 않은 기관은 활성이 될 수 없다",
    operationId: "createSourceConnection",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "connection.configure",
    implemented: true,
    requestSchema: connectionConfigureRequest,
    responseSchema: sourceConnectionEntry,
  },
  {
    method: "patch",
    path: "/api/v1/source-connections/{connectionId}",
    summary: "연동 갱신 — endpoint·상태·이용조건을 바꾼다",
    operationId: "updateSourceConnection",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "connection.configure",
    implemented: true,
    requestSchema: connectionConfigureRequest,
    responseSchema: sourceConnectionEntry,
  },
  {
    method: "get",
    path: "/api/v1/jurisdictions/{jurisdiction}/profile",
    summary: "관할별 연동 현황 — 미확인 통합을 과장하지 않는다",
    operationId: "getJurisdictionProfile",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: jurisdictionProfileView,
  },

  {
    method: "post",
    path: "/api/v1/source-connections/{connectionId}/collect",
    summary: "공식 출처 조회 — 실패도 Source Receipt로 남긴다",
    operationId: "collectFromSource",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.collect",
    implemented: true,
    requestSchema: sourceCollectRequest,
    responseSchema: sourceCollectResult,
  },

  // --- Governance (R4) ----------------------------------------------------
  {
    method: "get",
    path: "/api/v1/governance/proposals",
    summary: "제안 목록 — protocol과 project space를 함께 본다",
    operationId: "listProposals",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: governanceProposal.array(),
  },
  {
    method: "get",
    path: "/api/v1/governance/proposals/{proposalId}",
    summary: "제안 조회 — 집계와 지나온 경로를 함께 반환한다",
    operationId: "getProposal",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: governanceProposal,
  },
  {
    method: "post",
    path: "/api/v1/governance/proposals",
    summary: "제안 생성 — space 밖의 대상은 거절한다",
    operationId: "createProposal",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "governance.propose",
    implemented: true,
    requestSchema: createProposalRequest,
    responseSchema: governanceProposal,
  },
  {
    method: "post",
    path: "/api/v1/governance/proposals/{proposalId}/transitions",
    summary: "제안 상태 전이 — 집계 결과를 함께 굳힌다",
    operationId: "transitionProposal",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "governance.propose",
    implemented: true,
    requestSchema: transitionProposalRequest,
    responseSchema: governanceProposal,
  },
  {
    method: "post",
    path: "/api/v1/governance/proposals/{proposalId}/votes",
    summary: "투표 — 투표 기간에만 받는다",
    operationId: "castVote",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "governance.vote",
    implemented: true,
    requestSchema: castVoteRequest,
    responseSchema: governanceProposal,
  },

  // --- 워크스페이스 집계 ------------------------------------
  {
    method: "get",
    path: "/api/v1/my-work",
    summary: "내가 해야 하는 것과 내가 기다리는 것 — 섞지 않고 갈라 낸다",
    operationId: "getMyWork",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "project.read",
    implemented: true,
    responseSchema: myWork,
  },
  {
    method: "get",
    path: "/api/v1/me/activity",
    summary: "내가 한 일의 기록 — 이 지갑의 주체가 남긴 감사 기록, 본인만",
    operationId: "getMyActivity",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: myActivityQuery,
    responseSchema: myActivity,
  },
  {
    method: "get",
    path: "/api/v1/registry-entries",
    summary: "세 registry의 게시 상태 — 프로젝트를 열지 않고 본다",
    operationId: "listRegistryEntries",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "registry.read",
    implemented: true,
    responseSchema: registryEntrySummary.array(),
  },

  {
    method: "get",
    path: "/api/v1/notifications",
    summary: "내게 온 것과 내 역할에게 온 것 — 읽음은 사람마다 다르다",
    operationId: "listNotifications",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "project.read",
    implemented: true,
    responseSchema: notification.array(),
  },
  {
    method: "post",
    path: "/api/v1/notifications/{notificationId}/read",
    summary: "읽음 표시 — 나에 대해서만이다. 역할 알림은 남에게 남는다",
    operationId: "markNotificationRead",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "project.read",
    implemented: true,
    responseSchema: notification,
  },

  // --- 플랫폼 관리 -----------------------------------------
  //
  // tenant 생성은 여기 없다. 이유는 `apps/api/src/routes/admin.ts` 머리말.
  {
    method: "get",
    path: "/api/v1/admin/subjects",
    summary: "주체·지갑·역할을 한 번에 — 로그인 불가 계정이 흩어져 보이지 않게",
    operationId: "listAdminSubjects",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "admin.read",
    implemented: true,
    responseSchema: adminSubject.array(),
  },
  {
    method: "post",
    path: "/api/v1/admin/subjects",
    summary: "주체 등록 — bootstrap CLI 없이 사람을 추가한다",
    operationId: "createAdminSubject",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "admin.subject.manage",
    implemented: true,
    requestSchema: createSubjectRequest,
    responseSchema: adminSubject,
  },
  {
    method: "post",
    path: "/api/v1/admin/subjects/{subjectId}/wallets",
    summary: "지갑 바인딩 — 분실 키를 끊은 뒤 새 키를 붙이는 경로이기도 하다",
    operationId: "bindAdminWallet",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "admin.wallet.manage",
    implemented: true,
    requestSchema: bindWalletRequest,
    responseSchema: adminSubject,
  },
  {
    method: "post",
    path: "/api/v1/admin/wallets/{walletId}/disable",
    summary: "지갑 비활성 — 사유 코드를 남긴다(AC-27)",
    operationId: "disableAdminWallet",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "admin.wallet.manage",
    implemented: true,
    requestSchema: disableWalletRequest,
    responseSchema: adminSubject,
  },
  {
    method: "get",
    path: "/api/v1/admin/notification-sinks",
    summary: "알림 수신처와 그 배달 상태 — 보내지 못하고 있는 것을 함께 낸다",
    operationId: "listNotificationSinks",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "admin.notification.manage",
    implemented: true,
    responseSchema: notificationSink.array(),
  },
  {
    method: "post",
    path: "/api/v1/admin/notification-sinks",
    summary: "알림 수신처 등록 — 비밀은 참조로만 받는다",
    operationId: "createNotificationSink",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "admin.notification.manage",
    implemented: true,
    requestSchema: createNotificationSinkRequest,
    responseSchema: notificationSink,
  },
  {
    method: "post",
    path: "/api/v1/admin/notification-sinks/{sinkId}/state",
    summary: "수신처 일시정지·재개 — 지우지 않는다. 지우면 왜 끊겼는지가 남지 않는다",
    operationId: "updateNotificationSinkState",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "admin.notification.manage",
    implemented: true,
    requestSchema: updateNotificationSinkRequest,
    responseSchema: notificationSink,
  },
  {
    method: "get",
    path: "/api/v1/admin/role-grants",
    summary: "역할 부여 제안 목록 — 누가 무엇을 기다리는지",
    operationId: "listRoleGrants",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "admin.read",
    implemented: true,
    responseSchema: roleGrantRequest.array(),
  },
  {
    method: "post",
    path: "/api/v1/admin/role-grants",
    summary: "역할 부여 제안 — 승인은 다른 사람이 한다(02 §2.8)",
    operationId: "createRoleGrant",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "admin.role.propose",
    implemented: true,
    requestSchema: createRoleGrantRequest,
    responseSchema: roleGrantRequest,
  },
  {
    method: "post",
    path: "/api/v1/admin/role-grants/{grantId}/decision",
    summary: "역할 부여 승인·반려 — 제안자 자신은 할 수 없다",
    operationId: "decideRoleGrant",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "admin.role.approve",
    implemented: true,
    requestSchema: decideRoleGrantRequest,
    responseSchema: roleGrantRequest,
  },

  // --- 관측 ---------------------------------------------------------------
  {
    method: "get",
    path: "/api/v1/audit-events",
    summary: "감사 로그 조회 — append-only 기록을 읽는 유일한 경로",
    operationId: "listAuditEvents",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "audit.read",
    implemented: true,
    responseSchema: auditEvent.array(),
  },
  {
    method: "get",
    path: "/api/v1/outbox-backlog",
    summary: "이벤트 발행 지연 — 사라진 것이 아니라 늦어진 것을 구분한다",
    operationId: "getOutboxBacklog",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "audit.read",
    implemented: true,
    responseSchema: outboxBacklog,
  },

  // --- Public (무인증) -----------------------------------------------------
  {
    method: "get",
    path: "/api/v1/public/registries/{registryType}",
    summary: "공개 Registry 목록·검색 — 식별자를 몰라도 무엇이 있는지 볼 수 있다",
    operationId: "listPublicRegistryEntries",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: publicRegistryListQuery,
    responseSchema: publicRegistryList,
  },
  {
    method: "get",
    path: "/api/v1/public/registries/{registryType}/{publicKey}",
    summary: "공개 Registry projection 조회",
    operationId: "getPublicRegistryEntry",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: publicProjection,
  },
  {
    method: "get",
    path: "/api/v1/public/projection-fields",
    summary: "공개 projection이 노출할 수 있는 필드 목록",
    operationId: "getPublicProjectionFields",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: publicProjection,
  },
  {
    method: "get",
    path: "/api/v1/public/search",
    summary: "공개 통합 검색 — registry key, transaction hash, Merkle root, leaf hash",
    operationId: "searchPublicRecords",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: publicSearchQuery,
    responseSchema: publicSearchResult,
  },
  {
    method: "get",
    path: "/api/v1/public/proofs/{entryVersionId}",
    summary: "inclusion proof 조회 — 무결성 포함만 확인한다",
    operationId: "getInclusionProof",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: inclusionProofResponse,
  },
  {
    method: "get",
    path: "/api/v1/public/governance/proposals",
    summary: "공개 protocol 제안 목록 — project space와 draft는 내지 않는다",
    operationId: "listPublicProposals",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: publicCursorQuery,
    responseSchema: publicProposalList,
  },
  {
    method: "get",
    path: "/api/v1/public/governance/proposals/{proposalId}",
    summary: "공개 protocol 제안 하나 — 집계와 지나온 경로를 함께 낸다",
    operationId: "getPublicProposal",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: publicProposalDetail,
  },
  {
    method: "get",
    path: "/api/v1/public/disclosures",
    summary: "공개 정정·철회 시계열 — 덮지 않는 사건 종류를 응답이 밝힌다",
    operationId: "listPublicDisclosures",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: publicCursorQuery,
    responseSchema: publicDisclosureList,
  },
];

/** mutation route는 전부 action이 있어야 한다. 없으면 authorization 대상이 누락된 것이다. */
export function findRoutesWithoutAction(): RouteDefinition[] {
  return ROUTES.filter((route) => route.mutation && route.action === null);
}

/** 구현이 끝난 route. parity 테스트가 이 목록과 실제 등록 라우트를 대조한다. */
export function implementedRoutes(): RouteDefinition[] {
  return ROUTES.filter((route) => route.implemented);
}

/** 계약에만 있고 아직 구현되지 않은 route. release별로 남은 작업을 보여준다. */
export function plannedRoutes(): RouteDefinition[] {
  return ROUTES.filter((route) => !route.implemented);
}

/**
 * OpenAPI 경로(`{id}`)를 Fastify 경로(`:id`)로 바꾼다.
 * 두 표기가 다르기 때문에 자동 대조에는 정규화가 필요하다.
 */
export function toFastifyPath(openApiPath: string): string {
  return openApiPath.replace(/\{([^}]+)\}/g, ":$1");
}
