import { z } from "zod";
import {
  myActivity,
  myActivityQuery,
  publicSearchQuery,
  publicSearchResult,
} from "./resources.js";
import {
  createDocumentLinkRequest,
  createDocumentLinkRuleRequest,
  documentGraph,
  documentImpact,
  documentImpactList,
  documentImpactPreview,
  documentLink,
  documentLinkRule,
  removeDocumentLinkRequest,
  resolveDocumentImpactsRequest,
  retireDocumentLinkRuleRequest,
  updateDocumentProfileRequest,
} from "./resources.js";
import {
  adminSubject,
  anchorBatchStatus,
  attestationDispute,
  bindWalletRequest,
  auditEvent,
  authorityEntry,
  jurisdictionProfileView,
  authorityRegisterRequest,
  authorityStateRequest,
  authorityUpdateRequest,
  authorityVersionEntry,
  connectionConfigureRequest,
  offeringGateStatus,
  sourceConnectionEntry,
  evidenceStaleSignal,
  resolveStaleSignalRequest,
  secondReviewRequest,
  sourceCollectRequest,
  sourceCollectResult,
  createAttestationRequest,
  objectUpload,
  scannerStatus,
  uploadDownloadLink,
  createGateDecisionRequest,
  createProjectRequest,
  createRoleGrantRequest,
  createNotificationSinkRequest,
  createSubjectRequest,
  decideRoleGrantRequest,
  createRoleRevocationRequest,
  decideRoleRevocationRequest,
  roleRevocationRequest,
  decideRegistryProposalRequest,
  disableWalletRequest,
  proposeAttestationSchemaRequest,
  proposeCredentialRequest,
  proposePolicySetRequest,
  registryProposal,
  createProposalRequest,
  castVoteRequest,
  disputeAttestationRequest,
  governanceProposal,
  transitionProposalRequest,
  claim,
  gateDecision,
  inclusionProofResponse,
  projectSummary,
  projectLifecycle,
  projectLifecycleTransitionRequest,
  publicProjection,
  publicCursorQuery,
  publicDisclosureList,
  publicProposalDetail,
  publicProposalList,
  publicRegistryList,
  publicRegistryListQuery,
  readinessAssessment,
  registryEntryVersion,
  registryEntrySummary,
  myWork,
  notification,
  notificationSink,
  organizationSummary,
  reviewAssignmentOptions,
  updateNotificationSinkRequest,
  outboxBacklog,
  resolveDisputeRequest,
  roleGrantRequest,
  sourceReceipt,
  transitionCaseRequest,
  verificationAttestation,
  verificationCaseSummary,
} from "./resources.js";
import {
  sessionResponse,
  signatureRequestResponse,
  siweNonceRequest,
  siweNonceResponse,
  siweVerifyRequest,
  submitSignatureRequest,
} from "./auth.js";

/**
 * Route definitions — spec 07 §7.2.
 *
 * A path not listed here does not exist. In particular, the absence of any path
 * that modifies a readiness result is the control (REQ-DAPP-017) — it is not
 * blocked by permissions; it is never built.
 */

export interface RouteDefinition {
  readonly method: "get" | "post" | "patch" | "delete";
  readonly path: string;
  readonly summary: string;
  readonly operationId: string;
  /** Whether this is an unauthenticated public route (§7.1). */
  readonly public: boolean;
  /** Mutations require Idempotency-Key. */
  readonly mutation: boolean;
  /** Versioned resource mutations require If-Match. */
  readonly requiresIfMatch: boolean;
  readonly action: string | null;
  /**
   * Whether this route is actually implemented.
   *
   * The contract holds the target API and the implementation follows it. Without
   * distinguishing the two, people assume "it's in the contract, so it exists",
   * and conversely routes that are implemented but not in the contract quietly
   * accumulate. The parity test in `apps/api` uses this flag to catch drift in
   * both directions.
   */
  readonly implemented: boolean;
  /** Planned release. Meaningful only when `implemented: false`. */
  readonly plannedRelease?: "R1" | "R2" | "R3" | "R6";
  readonly requestSchema?: z.ZodTypeAny;
  /**
   * Query string contract.
   *
   * Pagination, sorting, and filters attach to body-less GETs, so `requestSchema`
   * cannot express them. Left out of the contract, they would not appear in
   * OpenAPI either, and clients would have to read code to learn what they can
   * send.
   */
  readonly querySchema?: z.ZodTypeAny;
  readonly responseSchema: z.ZodTypeAny;
}

export const ROUTES: readonly RouteDefinition[] = [
  // --- Auth ---------------------------------------------------------------
  {
    method: "post",
    path: "/api/v1/auth/siwe/nonce",
    summary: "Issue a SIWE login challenge nonce",
    operationId: "createSiweNonce",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    requestSchema: siweNonceRequest,
    responseSchema: siweNonceResponse,
  },
  {
    method: "post",
    path: "/api/v1/auth/siwe/verify",
    summary: "Verify a SIWE signature and issue a session",
    operationId: "verifySiweSignature",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    requestSchema: siweVerifyRequest,
    responseSchema: sessionResponse,
  },
  {
    method: "post",
    path: "/api/v1/auth/logout",
    summary: "Revoke the session token — invalid immediately",
    operationId: "logout",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: sessionResponse,
  },
  {
    method: "get",
    path: "/api/v1/auth/session",
    summary: "Get the current identity, roles, and assurance level",
    operationId: "getSession",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: sessionResponse,
  },

  // --- Project ------------------------------------------------------------
  {
    method: "post",
    path: "/api/v1/projects",
    summary: "Register a project",
    operationId: "createProject",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "project.create",
    implemented: true,
    requestSchema: createProjectRequest,
    responseSchema: projectSummary,
  },
  {
    method: "get",
    path: "/api/v1/projects",
    summary: "List projects in the current tenant",
    operationId: "listProjects",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: projectSummary.array(),
  },
  {
    method: "get",
    path: "/api/v1/projects/{projectId}",
    summary: "Get a project",
    operationId: "getProject",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: projectSummary,
  },
  {
    method: "get",
    path: "/api/v1/organizations",
    summary: "Organizations this account may name as a project owner — the same rule project creation enforces",
    operationId: "listOrganizations",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "project.create",
    implemented: true,
    responseSchema: organizationSummary.array(),
  },

  // --- Evidence -----------------------------------------------------------
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/source-receipts",
    summary: "List Source Receipts",
    operationId: "listSourceReceipts",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: sourceReceipt.array(),
  },
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/claims",
    summary: "List claims",
    operationId: "listClaims",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: claim.array(),
  },

  {
    method: "post",
    path: "/api/v1/projects/{projectId}/source-receipts",
    summary: "Register a Source Receipt — API, document, and manual check share one envelope",
    operationId: "createSourceReceipt",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    responseSchema: sourceReceipt,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/claims",
    summary: "Register a claim — domain rules compute the grade",
    operationId: "createClaim",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "claim.curate",
    implemented: true,
    responseSchema: claim,
  },
  {
    method: "post",
    path: "/api/v1/claims/{claimId}/conflicts",
    summary: "Record a claim conflict — recomputes the grade immediately",
    operationId: "createClaimConflict",
    public: false,
    mutation: true,
    // Grade recomputation bumps the claim version. The caller must state which
    // version it saw so concurrent writes cannot silently overwrite a judgment.
    requiresIfMatch: true,
    action: "claim.curate",
    implemented: true,
    responseSchema: claim,
  },

  // --- Uploads --------------------------------------------------------------
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/uploads",
    summary: "List uploads — also reports whether the scanner is alive",
    operationId: "listUploads",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    // Returns `items` and `scanner` together. From the list alone, "waiting" and
    // "nobody to scan" look the same.
    responseSchema: z.object({ items: objectUpload.array(), scanner: scannerStatus }),
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/uploads",
    summary: "Upload a file — lands in quarantine first",
    operationId: "createUpload",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    responseSchema: objectUpload,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/uploads/stream",
    summary: "Upload a file (multipart) — large files are not buffered in memory",
    operationId: "createUploadStream",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    responseSchema: objectUpload,
  },
  {
    method: "post",
    path: "/api/v1/uploads/{uploadId}/scan-result",
    summary: "Record a scan result — called by the scan service; an infected verdict is irreversible",
    operationId: "recordScanResult",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    // Uses a separate action so uploaders cannot pass their own files.
    action: "upload.scan_result",
    implemented: true,
    responseSchema: objectUpload,
  },
  {
    method: "post",
    path: "/api/v1/uploads/{uploadId}/promote",
    summary: "Promote to evidence — only scanned-clean uploads qualify",
    operationId: "promoteUpload",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "source.upload",
    implemented: true,
    responseSchema: objectUpload,
  },
  {
    method: "post",
    path: "/api/v1/uploads/{uploadId}/download-link",
    summary: "Short-lived download link — no permanent URL is created",
    operationId: "createUploadDownloadLink",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    responseSchema: uploadDownloadLink,
  },

  // --- Verification -------------------------------------------------------
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/verification-cases",
    summary: "List review cases — how assigned reviewers find their cases",
    operationId: "listVerificationCases",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: verificationCaseSummary.array(),
  },
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/review-assignment-options",
    summary: "Reviewers, credentials, and schemas a review assignment on this project can use",
    operationId: "getReviewAssignmentOptions",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    // Same action as creating the assignment — only the assigner needs the candidates.
    action: "claim.curate",
    implemented: true,
    responseSchema: reviewAssignmentOptions,
  },
  {
    method: "post",
    path: "/api/v1/verification-cases/{caseId}/transitions",
    summary: "Transition a review case — records change requests, declines, and cancellations",
    operationId: "transitionVerificationCase",
    public: false,
    mutation: true,
    // The state itself changes, not just the case version. If two people record
    // different decisions on one case concurrently, one silently disappears.
    requiresIfMatch: true,
    action: "claim.curate",
    implemented: true,
    requestSchema: transitionCaseRequest,
    responseSchema: verificationCaseSummary,
  },
  {
    method: "post",
    path: "/api/v1/attestations/{attestationId}/disputes",
    summary: "Dispute a signed attestation — adds a state without erasing the signature",
    operationId: "disputeAttestation",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.dispute",
    implemented: true,
    requestSchema: disputeAttestationRequest,
    responseSchema: verificationAttestation,
  },
  {
    method: "get",
    path: "/api/v1/attestations/{attestationId}/disputes",
    summary: "List disputes — resolved ones included",
    operationId: "listDisputes",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: attestationDispute.array(),
  },
  {
    method: "post",
    path: "/api/v1/disputes/{disputeId}/resolution",
    summary: "Resolve a dispute — appends the outcome without erasing the record",
    operationId: "resolveDispute",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.dispute",
    implemented: true,
    requestSchema: resolveDisputeRequest,
    responseSchema: attestationDispute,
  },
  {
    method: "post",
    path: "/api/v1/verification-cases/{caseId}/attestations",
    summary: "Create an attestation draft (before signing)",
    operationId: "createAttestation",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.sign",
    implemented: true,
    requestSchema: createAttestationRequest,
    responseSchema: verificationAttestation,
  },
  {
    method: "post",
    path: "/api/v1/attestations/{attestationId}/signature-requests",
    summary: "Create an EIP-712 signature request — the server never signs on your behalf",
    operationId: "createSignatureRequest",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.sign",
    implemented: true,
    responseSchema: signatureRequestResponse,
  },
  {
    method: "post",
    path: "/api/v1/attestations/{attestationId}/signatures",
    summary: "Submit a signature made with the user's key — the server only recomputes and verifies",
    operationId: "submitAttestationSignature",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "attestation.sign",
    implemented: true,
    requestSchema: submitSignatureRequest,
    responseSchema: verificationAttestation,
  },

  {
    method: "post",
    path: "/api/v1/verification-cases",
    summary: "Create a Verification Case — freezes the evidence snapshot",
    operationId: "createVerificationCase",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "claim.curate",
    implemented: true,
    responseSchema: verificationAttestation,
  },

  // --- Readiness / Decision -----------------------------------------------
  //
  // No path PATCHes readiness. Only recomputation is possible (§7.2).
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/readiness-assessments",
    summary: "Recompute readiness — creates a new assessment without modifying existing results",
    operationId: "createReadinessAssessment",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "readiness.recompute",
    implemented: true,
    responseSchema: readinessAssessment,
  },
  {
    method: "get",
    path: "/api/v1/readiness-assessments/{assessmentId}",
    summary: "Get a readiness assessment",
    operationId: "getReadinessAssessment",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: readinessAssessment,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/gate-decisions",
    summary: "Record a human gate decision",
    operationId: "createGateDecision",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "gate.decide",
    implemented: true,
    requestSchema: createGateDecisionRequest,
    responseSchema: gateDecision,
  },

  // --- Registry -----------------------------------------------------------
  {
    method: "post",
    path: "/api/v1/registry-entries",
    summary: "Publish a version approved for disclosure — rejects fields outside the allowlist",
    operationId: "publishRegistryVersion",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "registry.publish",
    implemented: true,
    responseSchema: registryEntryVersion,
  },
  {
    method: "post",
    path: "/api/v1/registry-entries/{entryId}/revoke",
    summary: "Revoke a publication — adds a new state without deleting existing versions",
    operationId: "revokeRegistryVersion",
    public: false,
    mutation: true,
    // A new version may have been published since the read. State the intended version.
    requiresIfMatch: true,
    action: "registry.revoke",
    implemented: true,
    responseSchema: registryEntryVersion,
  },

  {
    method: "get",
    path: "/api/v1/anchor-batches",
    summary: "Anchor batch chain status — shows included and confirmed separately",
    operationId: "listAnchorBatches",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: anchorBatchStatus.array(),
  },
  {
    method: "post",
    path: "/api/v1/anchor-batches",
    summary: "Create a Merkle batch — includes only published versions",
    operationId: "createAnchorBatch",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "anchor.submit",
    implemented: true,
    responseSchema: registryEntryVersion,
  },

  {
    method: "post",
    path: "/api/v1/anchor-batches/{batchId}/resubmit",
    summary: "Resubmit a stuck anchor batch — a human decides, not automation",
    operationId: "resubmitAnchorBatch",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "anchor.submit",
    implemented: true,
    responseSchema: anchorBatchStatus,
  },

  {
    method: "post",
    path: "/api/v1/source-receipts/{receiptId}/second-review",
    summary: "Second review of a manual check — not by the person who did the first check",
    operationId: "recordSecondReview",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.collect",
    implemented: true,
    requestSchema: secondReviewRequest,
    responseSchema: sourceReceipt,
  },

  {
    method: "get",
    path: "/api/v1/projects/{projectId}/stale-signals",
    summary: "Outputs with shaken evidence — open and resolved signals together",
    operationId: "listStaleSignals",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: evidenceStaleSignal.array(),
  },
  {
    method: "post",
    path: "/api/v1/stale-signals/{signalId}/resolve",
    summary: "Resolve a signal — taking down a public record is never automated",
    operationId: "resolveStaleSignal",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "registry.revoke",
    implemented: true,
    requestSchema: resolveStaleSignalRequest,
    responseSchema: evidenceStaleSignal,
  },

  // --- Document relations ---------------------------------------------------
  //
  // A replacement or expiry travels along declared links as an impact — a request for a second
  // look. Nothing here changes or takes down a document.
  {
    method: "patch",
    path: "/api/v1/uploads/{uploadId}/document-profile",
    summary: "Set a document's type, validity date, or the document it replaces",
    operationId: "updateDocumentProfile",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "source.upload",
    implemented: true,
    requestSchema: updateDocumentProfileRequest,
    responseSchema: objectUpload,
  },
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/document-graph",
    summary: "Documents of a project with their active links, validity, and open impacts",
    operationId: "getDocumentGraph",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: documentGraph,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/document-links",
    summary: "Link two documents — the downstream one rests on the upstream one",
    operationId: "createDocumentLink",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    requestSchema: createDocumentLinkRequest,
    responseSchema: documentLink,
  },
  {
    method: "post",
    path: "/api/v1/document-links/{linkId}/removal",
    summary: "Remove a link with a reason — links are never deleted",
    operationId: "removeDocumentLink",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    requestSchema: removeDocumentLinkRequest,
    responseSchema: documentLink,
  },
  {
    method: "get",
    path: "/api/v1/uploads/{uploadId}/impact-preview",
    summary: "Documents that would need a second look if this one changed — nothing is recorded",
    operationId: "getDocumentImpactPreview",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: documentImpactPreview,
  },
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/document-impacts",
    summary: "Documents that need a second look — open first, judged ones kept",
    operationId: "listDocumentImpacts",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: documentImpactList,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/document-impacts/resolutions",
    summary: "Judge several impacts at once — all or nothing, a reason is required",
    operationId: "resolveDocumentImpacts",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.upload",
    implemented: true,
    requestSchema: resolveDocumentImpactsRequest,
    responseSchema: z.object({ items: documentImpact.array() }),
  },
  {
    method: "get",
    path: "/api/v1/document-link-rules",
    summary: "Operator type rules that link documents as they arrive",
    operationId: "listDocumentLinkRules",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: z.object({ items: documentLinkRule.array() }),
  },
  {
    method: "post",
    path: "/api/v1/document-link-rules",
    summary: "Declare a type rule — applied to current documents and to documents typed later",
    operationId: "createDocumentLinkRule",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "document.rule.manage",
    implemented: true,
    requestSchema: createDocumentLinkRuleRequest,
    responseSchema: documentLinkRule.extend({ linksCreated: z.number().int().nonnegative() }),
  },
  {
    method: "post",
    path: "/api/v1/document-link-rules/{ruleId}/retirement",
    summary: "Retire a type rule — the links it already made stay",
    operationId: "retireDocumentLinkRule",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "document.rule.manage",
    implemented: true,
    requestSchema: retireDocumentLinkRuleRequest,
    responseSchema: documentLinkRule,
  },

  // --- Asset/Offering gate (R6, OD-07) --------------------------------------
  //
  // There are no trading routes, only condition checks — an unapproved regulated
  // feature, even behind a flag, creates code, security, and operational
  // liability and a risk of accidental activation.
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/lifecycle",
    summary: "Lifecycle state and history — resumed-after-suspension differs from never suspended",
    operationId: "getProjectLifecycle",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "project.read",
    implemented: true,
    responseSchema: projectLifecycle,
  },
  {
    method: "post",
    path: "/api/v1/projects/{projectId}/lifecycle-transitions",
    summary: "Lifecycle transition — suspend needs one person; the suspender cannot resume",
    operationId: "transitionProjectLifecycle",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    // The actual check splits into two actions. The contract lists the broader
    // one and the route picks by `toState` — the asymmetry of 04 §4.3 lives here.
    action: "project.lifecycle.advance",
    implemented: true,
    requestSchema: projectLifecycleTransitionRequest,
    responseSchema: projectLifecycle,
  },
  {
    method: "get",
    path: "/api/v1/projects/{projectId}/offering-gate",
    summary: "Asset/offering activation conditions — returns what remains and who owns it",
    operationId: "getOfferingGate",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: offeringGateStatus,
  },

  // --- Authority Registry (R5) ---------------------------------------------
  {
    method: "get",
    path: "/api/v1/authorities",
    summary: "List authorities — includes what each does not prove and its connection status",
    operationId: "listAuthorities",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: authorityEntry.array(),
  },
  // Registration and approval are separate actions — 02 §2.8 forbids
  // operator-only `accepted` transitions. One route could not express that
  // separation as a permission.
  {
    method: "post",
    path: "/api/v1/authorities",
    summary: "Register an authority candidate — always starts at proposed",
    operationId: "registerAuthority",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "authority.register",
    implemented: true,
    requestSchema: authorityRegisterRequest,
    responseSchema: authorityEntry,
  },
  {
    method: "patch",
    path: "/api/v1/authorities/{authorityId}",
    summary: "Update an authority — every change is recorded in history",
    operationId: "updateAuthority",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "authority.register",
    implemented: true,
    requestSchema: authorityUpdateRequest,
    responseSchema: authorityEntry,
  },
  {
    method: "post",
    path: "/api/v1/authorities/{authorityId}/state",
    summary: "Transition authority state — the registrant cannot approve",
    operationId: "decideAuthorityState",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "authority.review",
    implemented: true,
    requestSchema: authorityStateRequest,
    responseSchema: authorityEntry,
  },
  {
    method: "get",
    path: "/api/v1/authorities/{authorityId}/versions",
    summary: "Authority history — what it claimed to prove at each point",
    operationId: "listAuthorityVersions",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: authorityVersionEntry.array(),
  },
  {
    method: "get",
    path: "/api/v1/authorities/{authorityId}/connections",
    summary: "List connections — credential values are never returned",
    operationId: "listSourceConnections",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: sourceConnectionEntry.array(),
  },
  {
    method: "post",
    path: "/api/v1/authorities/{authorityId}/connections",
    summary: "Configure a connection — an unapproved authority cannot become active",
    operationId: "createSourceConnection",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "connection.configure",
    implemented: true,
    requestSchema: connectionConfigureRequest,
    responseSchema: sourceConnectionEntry,
  },
  {
    method: "patch",
    path: "/api/v1/source-connections/{connectionId}",
    summary: "Update a connection — changes endpoint, state, and terms of use",
    operationId: "updateSourceConnection",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "connection.configure",
    implemented: true,
    requestSchema: connectionConfigureRequest,
    responseSchema: sourceConnectionEntry,
  },
  {
    method: "get",
    path: "/api/v1/jurisdictions/{jurisdiction}/profile",
    summary: "Connection status per jurisdiction — does not overstate unconfirmed integrations",
    operationId: "getJurisdictionProfile",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: jurisdictionProfileView,
  },

  {
    method: "post",
    path: "/api/v1/source-connections/{connectionId}/collect",
    summary: "Official source lookup — failures are recorded as Source Receipts too",
    operationId: "collectFromSource",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "source.collect",
    implemented: true,
    requestSchema: sourceCollectRequest,
    responseSchema: sourceCollectResult,
  },

  // --- Governance (R4) ----------------------------------------------------
  {
    method: "get",
    path: "/api/v1/governance/proposals",
    summary: "List proposals — protocol and project spaces together",
    operationId: "listProposals",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: governanceProposal.array(),
  },
  {
    method: "get",
    path: "/api/v1/governance/proposals/{proposalId}",
    summary: "Get a proposal — includes the tally and transition history",
    operationId: "getProposal",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: governanceProposal,
  },
  {
    method: "post",
    path: "/api/v1/governance/proposals",
    summary: "Create a proposal — rejects targets outside the space",
    operationId: "createProposal",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "governance.propose",
    implemented: true,
    requestSchema: createProposalRequest,
    responseSchema: governanceProposal,
  },
  {
    method: "post",
    path: "/api/v1/governance/proposals/{proposalId}/transitions",
    summary: "Transition a proposal — freezes the tally with it",
    operationId: "transitionProposal",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "governance.propose",
    implemented: true,
    requestSchema: transitionProposalRequest,
    responseSchema: governanceProposal,
  },
  {
    method: "post",
    path: "/api/v1/governance/proposals/{proposalId}/votes",
    summary: "Cast a vote — accepted only during the voting period",
    operationId: "castVote",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "governance.vote",
    implemented: true,
    requestSchema: castVoteRequest,
    responseSchema: governanceProposal,
  },

  // --- Workspace aggregates ------------------------------------
  {
    method: "get",
    path: "/api/v1/my-work",
    summary: "What I must do versus what I am waiting on — kept separate",
    operationId: "getMyWork",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "project.read",
    implemented: true,
    responseSchema: myWork,
  },
  {
    method: "get",
    path: "/api/v1/me/activity",
    summary: "My activity — audit records left by this wallet's subject, visible only to them",
    operationId: "getMyActivity",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: myActivityQuery,
    responseSchema: myActivity,
  },
  {
    method: "get",
    path: "/api/v1/registry-entries",
    summary: "Publication status across the three registries — without opening each project",
    operationId: "listRegistryEntries",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "registry.read",
    implemented: true,
    responseSchema: registryEntrySummary.array(),
  },

  {
    method: "get",
    path: "/api/v1/notifications",
    summary: "Notifications to me and to my roles — read state is per person",
    operationId: "listNotifications",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "project.read",
    implemented: true,
    responseSchema: notification.array(),
  },
  {
    method: "post",
    path: "/api/v1/notifications/{notificationId}/read",
    summary: "Mark as read — for me only; role notifications stay unread for others",
    operationId: "markNotificationRead",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "project.read",
    implemented: true,
    responseSchema: notification,
  },

  // --- Platform administration -----------------------------------------
  //
  // Tenant creation is not here. See the header of `apps/api/src/routes/admin.ts` for why.
  {
    method: "get",
    path: "/api/v1/admin/subjects",
    summary: "Subjects, wallets, and roles at once — so locked-out accounts are not scattered across views",
    operationId: "listAdminSubjects",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "admin.read",
    implemented: true,
    responseSchema: adminSubject.array(),
  },
  {
    method: "post",
    path: "/api/v1/admin/subjects",
    summary: "Register a subject — adds people without the bootstrap CLI",
    operationId: "createAdminSubject",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "admin.subject.manage",
    implemented: true,
    requestSchema: createSubjectRequest,
    responseSchema: adminSubject,
  },
  {
    method: "post",
    path: "/api/v1/admin/subjects/{subjectId}/wallets",
    summary: "Bind a wallet — also the path for attaching a new key after cutting off a lost one",
    operationId: "bindAdminWallet",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "admin.wallet.manage",
    implemented: true,
    requestSchema: bindWalletRequest,
    responseSchema: adminSubject,
  },
  {
    method: "post",
    path: "/api/v1/admin/wallets/{walletId}/disable",
    summary: "Disable a wallet — records a reason code (AC-27)",
    operationId: "disableAdminWallet",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "admin.wallet.manage",
    implemented: true,
    requestSchema: disableWalletRequest,
    responseSchema: adminSubject,
  },
  {
    method: "get",
    path: "/api/v1/admin/notification-sinks",
    summary: "Notification sinks and delivery status — includes what is failing to send",
    operationId: "listNotificationSinks",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "admin.notification.manage",
    implemented: true,
    responseSchema: notificationSink.array(),
  },
  {
    method: "post",
    path: "/api/v1/admin/notification-sinks",
    summary: "Register a notification sink — secrets accepted only by reference",
    operationId: "createNotificationSink",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "admin.notification.manage",
    implemented: true,
    requestSchema: createNotificationSinkRequest,
    responseSchema: notificationSink,
  },
  {
    method: "post",
    path: "/api/v1/admin/notification-sinks/{sinkId}/state",
    summary: "Pause or resume a sink — never deleted, since deletion loses why it stopped",
    operationId: "updateNotificationSinkState",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "admin.notification.manage",
    implemented: true,
    requestSchema: updateNotificationSinkRequest,
    responseSchema: notificationSink,
  },
  {
    method: "get",
    path: "/api/v1/admin/role-grants",
    summary: "List role grant proposals — who is waiting on what",
    operationId: "listRoleGrants",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "admin.read",
    implemented: true,
    responseSchema: roleGrantRequest.array(),
  },
  {
    method: "post",
    path: "/api/v1/admin/role-grants",
    summary: "Propose a role grant — approved by someone else (02 §2.8)",
    operationId: "createRoleGrant",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "admin.role.propose",
    implemented: true,
    requestSchema: createRoleGrantRequest,
    responseSchema: roleGrantRequest,
  },
  {
    method: "post",
    path: "/api/v1/admin/role-grants/{grantId}/decision",
    summary: "Approve or reject a role grant — not by the proposer",
    operationId: "decideRoleGrant",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "admin.role.approve",
    implemented: true,
    requestSchema: decideRoleGrantRequest,
    responseSchema: roleGrantRequest,
  },
  // Revocation reuses the grant actions: both change who holds which role, and what the
  // two-person rule separates is people, not roles. See `apps/api/src/routes/role-revocations.ts`.
  {
    method: "get",
    path: "/api/v1/admin/role-revocations",
    summary: "List role revocation proposals — who is waiting on what",
    operationId: "listRoleRevocations",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "admin.read",
    implemented: true,
    responseSchema: roleRevocationRequest.array(),
  },
  {
    method: "post",
    path: "/api/v1/admin/role-revocations",
    summary: "Propose revoking a role binding — approved by someone else (02 §2.8)",
    operationId: "createRoleRevocation",
    public: false,
    mutation: true,
    requiresIfMatch: false,
    action: "admin.role.propose",
    implemented: true,
    requestSchema: createRoleRevocationRequest,
    responseSchema: roleRevocationRequest,
  },
  {
    method: "post",
    path: "/api/v1/admin/role-revocations/{revocationId}/decision",
    summary: "Approve or reject a role revocation — not by the proposer",
    operationId: "decideRoleRevocation",
    public: false,
    mutation: true,
    requiresIfMatch: true,
    action: "admin.role.approve",
    implemented: true,
    requestSchema: decideRoleRevocationRequest,
    responseSchema: roleRevocationRequest,
  },

  // --- Review registries (02 §2.8) ---------------------------------------------------------
  ...reviewRegistryRoutes("credentials", "Credential", "credential", proposeCredentialRequest),
  ...reviewRegistryRoutes(
    "attestation-schemas",
    "AttestationSchema",
    "attestation schema",
    proposeAttestationSchemaRequest,
  ),
  ...reviewRegistryRoutes("policy-sets", "PolicySet", "compliance policy set", proposePolicySetRequest),

  // --- Observability ---------------------------------------------------------------
  {
    method: "get",
    path: "/api/v1/audit-events",
    summary: "Read the audit log — the only read path for append-only records",
    operationId: "listAuditEvents",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "audit.read",
    implemented: true,
    responseSchema: auditEvent.array(),
  },
  {
    method: "get",
    path: "/api/v1/outbox-backlog",
    summary: "Event publication backlog — distinguishes delayed from lost",
    operationId: "getOutboxBacklog",
    public: false,
    mutation: false,
    requiresIfMatch: false,
    action: "audit.read",
    implemented: true,
    responseSchema: outboxBacklog,
  },

  // --- Public (unauthenticated) -----------------------------------------------------
  {
    method: "get",
    path: "/api/v1/public/registries/{registryType}",
    summary: "List and search the public registry — browse without knowing identifiers",
    operationId: "listPublicRegistryEntries",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: publicRegistryListQuery,
    responseSchema: publicRegistryList,
  },
  {
    method: "get",
    path: "/api/v1/public/registries/{registryType}/{publicKey}",
    summary: "Get a public registry projection",
    operationId: "getPublicRegistryEntry",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: publicProjection,
  },
  {
    method: "get",
    path: "/api/v1/public/projection-fields",
    summary: "Fields a public projection may expose",
    operationId: "getPublicProjectionFields",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: publicProjection,
  },
  {
    method: "get",
    path: "/api/v1/public/search",
    summary: "Unified public search — registry key, transaction hash, Merkle root, leaf hash",
    operationId: "searchPublicRecords",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: publicSearchQuery,
    responseSchema: publicSearchResult,
  },
  {
    method: "get",
    path: "/api/v1/public/proofs/{entryVersionId}",
    summary: "Get an inclusion proof — confirms integrity and inclusion only",
    operationId: "getInclusionProof",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: inclusionProofResponse,
  },
  {
    method: "get",
    path: "/api/v1/public/governance/proposals",
    summary: "List public protocol proposals — excludes project space and drafts",
    operationId: "listPublicProposals",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: publicCursorQuery,
    responseSchema: publicProposalList,
  },
  {
    method: "get",
    path: "/api/v1/public/governance/proposals/{proposalId}",
    summary: "Get a public protocol proposal — includes the tally and transition history",
    operationId: "getPublicProposal",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    responseSchema: publicProposalDetail,
  },
  {
    method: "get",
    path: "/api/v1/public/disclosures",
    summary: "Public correction and revocation timeline — the response states which event kinds it does not cover",
    operationId: "listPublicDisclosures",
    public: true,
    mutation: false,
    requiresIfMatch: false,
    action: null,
    implemented: true,
    querySchema: publicCursorQuery,
    responseSchema: publicDisclosureList,
  },
];

/**
 * Proposal routes for one review registry — 02 §2.8.
 *
 * One set per registry so each propose route documents its own payload. Nothing is written to
 * the registry until someone other than the proposer approves.
 */
function reviewRegistryRoutes(
  segment: string,
  noun: string,
  label: string,
  requestSchema: z.ZodTypeAny,
): RouteDefinition[] {
  const base = `/api/v1/review-registry/${segment}/proposals`;
  const shared = { public: false, implemented: true } as const;
  return [
    {
      ...shared,
      method: "get",
      path: base,
      summary: `List ${label} proposals — pending and decided`,
      operationId: `list${noun}Proposals`,
      mutation: false,
      requiresIfMatch: false,
      action: "review_registry.read",
      responseSchema: registryProposal.array(),
    },
    {
      ...shared,
      method: "post",
      path: base,
      summary: `Propose a ${label} — nothing is created until another person approves`,
      operationId: `propose${noun}`,
      mutation: true,
      requiresIfMatch: false,
      action: "review_registry.propose",
      requestSchema,
      responseSchema: registryProposal,
    },
    {
      ...shared,
      method: "get",
      path: `${base}/{proposalId}`,
      summary: `Get one ${label} proposal`,
      operationId: `get${noun}Proposal`,
      mutation: false,
      requiresIfMatch: false,
      action: "review_registry.read",
      responseSchema: registryProposal,
    },
    {
      ...shared,
      method: "post",
      path: `${base}/{proposalId}/decision`,
      summary: `Approve or reject a ${label} proposal — not by the proposer`,
      operationId: `decide${noun}Proposal`,
      mutation: true,
      requiresIfMatch: true,
      action: "review_registry.approve",
      requestSchema: decideRegistryProposalRequest,
      responseSchema: registryProposal,
    },
  ];
}

/** Every mutation route must have an action. A missing one means authorization was skipped. */
export function findRoutesWithoutAction(): RouteDefinition[] {
  return ROUTES.filter((route) => route.mutation && route.action === null);
}

/** Implemented routes. The parity test compares this list with the actually registered routes. */
export function implementedRoutes(): RouteDefinition[] {
  return ROUTES.filter((route) => route.implemented);
}

/** Routes in the contract but not yet implemented. Shows remaining work per release. */
export function plannedRoutes(): RouteDefinition[] {
  return ROUTES.filter((route) => !route.implemented);
}

/**
 * Converts an OpenAPI path (`{id}`) to a Fastify path (`:id`).
 * The notations differ, so automated comparison needs normalization.
 */
export function toFastifyPath(openApiPath: string): string {
  return openApiPath.replace(/\{([^}]+)\}/g, ":$1");
}
