/**
 * tokens/ + content/ → docs/*.md and ai/CLAUDE.md
 *
 *   node scripts/docs.mjs
 *
 * Two audiences, one source. `docs/` is for a person deciding what to use;
 * `ai/CLAUDE.md` is the compressed form a coding agent loads into context when
 * a consuming project adopts the system. Generating both from the same data is
 * what stops the agent and the human from being told different things.
 *
 * Korean-primary with the English string in its own column: the readers are
 * this team, and a duplicate English document would drift.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { toHex } from "../lib/color.mjs";
import { loadTokens } from "../lib/tokens.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const version = JSON.parse(readFileSync(`${ROOT}/package.json`, "utf8")).version;
const read = (file) => JSON.parse(readFileSync(`${ROOT}/${file}`, "utf8"));

const tokens = [...loadTokens(`${ROOT}/tokens`).values()];
const voice = read("content/voice.json");
const patterns = read("content/patterns.json");
const logo = read("content/logo.json");

const GENERATED = `<!-- GENERATED by scripts/docs.mjs — do not edit. Source: tokens/ and content/. -->`;

const table = (rows) => rows.map((cells) => `| ${cells.join(" | ")} |`).join("\n");
const header = (cells) => table([cells, cells.map(() => "---")]);
const code = (s) => `\`${s}\``;
const ko = (pair) => pair?.ko ?? "";
const en = (pair) => pair?.en ?? "";

mkdirSync(`${ROOT}/docs`, { recursive: true });
mkdirSync(`${ROOT}/ai`, { recursive: true });

/* ── docs/tokens.md ────────────────────────────────────────────────── */

const groups = patterns.groups.map((g) => g.id).concat("print");
const groupTitle = Object.fromEntries(
  patterns.groups.map((g) => [g.id, `${g.title.ko} · ${g.title.en}`]),
);
groupTitle.print = "인쇄 · Print";

const groupNote = Object.fromEntries(patterns.groups.map((g) => [g.id, g.note.ko]));
groupNote.print =
  "CSS 변수가 없는 참조 전용 값입니다. 화면 표면과 인쇄 표면은 서로 다른 구리색을 요구하므로 두 세트를 섞지 않습니다.";

const tokenSections = groups
  .map((id) => {
    const rows = tokens.filter((t) => t.group === id);
    if (rows.length === 0) return null;
    return [
      `### ${groupTitle[id] ?? id}`,
      "",
      groupNote[id] ?? "",
      "",
      header(["토큰", "값", "Hex", "용도", "Use (EN)"]),
      table(
        rows.map((t) => [
          t.cssVar ? code(`--${t.name}`) : `${code(t.name)} *`,
          code(t.value),
          t.type === "color" ? toHex(t.value) : "—",
          t.note ? `${ko(t.use)}<br>**비고:** ${ko(t.note)}` : ko(t.use),
          en(t.use) || t.description,
        ]),
      ),
    ].join("\n");
  })
  .filter(Boolean)
  .join("\n\n");

writeFileSync(
  `${ROOT}/docs/tokens.md`,
  `${GENERATED}

# 디자인 토큰 · Design tokens

\`@mpc/design\` ${version} · 토큰 ${tokens.length}개 (CSS 변수 ${tokens.filter((t) => t.cssVar).length}개)

정본은 \`tokens/*.json\` 하나뿐입니다. 이 문서도, \`dist/\`의 CSS·JSON·SCSS·Dart도
전부 거기서 생성됩니다. \`*\` 표시는 CSS 변수를 만들지 않는 참조 전용 값입니다.

${tokenSections}

## 유틸리티 클래스

\`dist/utilities.css\`가 정의하는 클래스입니다. **모션** 열의 ✓는
\`prefers-reduced-motion\` 블록이 해당 클래스를 직접 해제한다는 뜻입니다.

${header(["클래스", "모션", "용도", "Use (EN)"])}
${table(
  patterns.utilities.map((u) => [
    code(`.${u.className}`),
    u.animated ? "✓" : "",
    ko(u.use),
    en(u.use),
  ]),
)}
`,
);

/* ── docs/patterns.md ──────────────────────────────────────────────── */

writeFileSync(
  `${ROOT}/docs/patterns.md`,
  `${GENERATED}

# 패턴 · Patterns

스택과 무관한 구성 규칙입니다. 이 시스템을 채택한 프로젝트가 프레임워크와
관계없이 물려받는 내용입니다.

## 시스템 규칙

${patterns.rules.map((r) => `- **${r.rule.ko}**\n  - ${r.why.ko}\n  - _${r.rule.en}_`).join("\n")}

## 컴포넌트 계층

컴포넌트를 여섯 종류로 나누고 각각에 하나의 규칙을 겁니다. 어떤 UI 프레임워크를
쓰든 이 구분은 유지됩니다.

${header(["계층", "규칙", "Rule (EN)"])}
${table(patterns.layers.map((l) => [`**${l.title.ko}** (${l.title.en})`, l.rule.ko, l.rule.en]))}

## 토큰 그룹의 의도

${patterns.groups.map((g) => `- **${g.title.ko}** — ${g.note.ko}`).join("\n")}
`,
);

/* ── docs/voice.md ─────────────────────────────────────────────────── */

writeFileSync(
  `${ROOT}/docs/voice.md`,
  `${GENERATED}

# 톤 · Voice

이 문서의 규칙은 문체 취향이 아닙니다. MPC는 발행 전 단계의 금융 상품을
서술하며, 아래 대부분은 잘못된 문장이 나쁜 문장이 아니라 컴플라이언스 문제가
되기 때문에 존재합니다.

## 포지셔닝

> **${voice.positioning.statement.ko}**
>
> ${voice.positioning.expansion.ko}

> _${voice.positioning.statement.en}_
>
> _${voice.positioning.expansion.en}_

## 하지 않는 주장

${header(["주장하지 않음", "대신"])}
${table(voice.boundaries.map((b) => [`**${b.claim.ko}**`, b.instead.ko]))}

## 톤 규칙

${voice.tone
  .map((t) =>
    [
      `### ${t.rule.ko}`,
      "",
      t.why.ko,
      t.example ? `\n> 예: ${t.example.ko}` : "",
      `\n_${t.rule.en}_`,
    ].join("\n"),
  )
  .join("\n\n")}

## 이중 언어 정책

${voice.locale.map((p) => `- **${p.rule.ko}**\n  - ${p.why.ko}`).join("\n")}
`,
);

/* ── docs/logo.md ──────────────────────────────────────────────────── */

writeFileSync(
  `${ROOT}/docs/logo.md`,
  `${GENERATED}

# 로고 · Logo

에셋은 \`assets/logo/\`에 있습니다. 벡터로 확대·축소가 가능한 곳에서는 SVG를
사용합니다. 워드마크는 아웃라인 처리되어 있어 서체 설치 없이 렌더됩니다.

## 기하 제약

${header(["규칙", "값", "이유"])}
${table(logo.constraints.map((c) => [c.label.ko, c.value.ko, c.why.ko]))}

## 금지

${logo.donts.map((d) => `- ${d.ko}`).join("\n")}

## 서체

${header(["서체", "역할", "굵기", "라이선스"])}
${table(logo.typefaces.map((f) => [f.family, f.role.ko, f.weights, f.license]))}

셋 다 오픈 라이선스이므로 파트너·언론 자료에 라이선스 구매 없이 사용할 수 있습니다.

## 상표

${logo.trademark.ko}

${logo.trademark.en}

_${logo.trademark.status}_
`,
);

/* ── ai/CLAUDE.md ──────────────────────────────────────────────────── */

/** One line per rule. An agent reads this; it does not need the reasoning. */
const bullets = (items, pick) => items.map((i) => `- ${pick(i)}`).join("\n");

writeFileSync(
  `${ROOT}/ai/CLAUDE.md`,
  `<!-- GENERATED by @mpc/design ${version} scripts/docs.mjs. Regenerate rather than edit. -->

## MPC 디자인 시스템 (@mpc/design ${version})

이 프로젝트는 MPC 디자인 시스템을 따른다. 아래는 강제 규칙이다.

### 색·치수

- 색은 반드시 토큰으로 작성한다. 리터럴 색상값 금지.
- 사용 가능한 CSS 변수: ${tokens
    .filter((t) => t.cssVar && t.type === "color")
    .map((t) => `\`--${t.name}\``)
    .join(", ")}
- 라운드: ${tokens
    .filter((t) => t.type === "dimension")
    .map((t) => `\`--${t.name}\``)
    .join(", ")}. 이보다 큰 값을 쓰지 않는다.
- 서체: ${tokens
    .filter((t) => t.type === "fontFamily")
    .map((t) => `\`--${t.name}\``)
    .join(", ")}.
- 전체 목록과 각 토큰의 용도는 \`docs/tokens.md\` 참조.

### 구성

${bullets(patterns.rules, (r) => r.rule.ko)}

### 컴포넌트 계층

${bullets(patterns.layers, (l) => `**${l.title.ko}** — ${l.rule.ko}`)}

### 글을 쓸 때

포지셔닝: ${voice.positioning.statement.ko}

하지 않는 주장:

${bullets(voice.boundaries, (b) => `${b.claim.ko} 대신: ${b.instead.ko}`)}

톤:

${bullets(voice.tone, (t) => t.rule.ko)}

이중 언어:

${bullets(voice.locale, (p) => p.rule.ko)}

### 로고

${bullets(logo.constraints, (c) => `${c.label.ko}: ${c.value.ko}`)}

금지:

${bullets(logo.donts, (d) => d.ko)}
`,
);

console.log(
  `docs/  (tokens.md ${tokens.length} tokens, patterns.md ${patterns.rules.length} rules + ` +
    `${patterns.layers.length} layers, voice.md ${voice.tone.length} tone rules, ` +
    `logo.md ${logo.constraints.length} constraints)\nai/CLAUDE.md`,
);
