/**
 * tokens/ + content/ → docs/*.md and ai/CLAUDE.md
 *
 *   node scripts/docs.mjs
 *
 * Two audiences, one source. `docs/` is for a person deciding what to use;
 * `ai/CLAUDE.md` is the compressed form a coding agent loads into context when
 * a consuming project adopts the system. Generating both from the same data is
 * what stops the agent and the human from being told different things.
 *
 * English only. The Korean strings stay in tokens/ and content/ as the `ko`
 * half of each pair: they are product copy for the Korean locale, and a second
 * rendering of every document would drift.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { toHex } from "../lib/color.mjs";
import { loadTokens } from "../lib/tokens.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const version = JSON.parse(readFileSync(`${ROOT}/package.json`, "utf8")).version;
const read = (file) => JSON.parse(readFileSync(`${ROOT}/${file}`, "utf8"));

const tokens = [...loadTokens(`${ROOT}/tokens`).values()];
const voice = read("content/voice.json");
const patterns = read("content/patterns.json");
const logo = read("content/logo.json");

const GENERATED = `<!-- GENERATED by scripts/docs.mjs — do not edit. Source: tokens/ and content/. -->`;

const table = (rows) => rows.map((cells) => `| ${cells.join(" | ")} |`).join("\n");
const header = (cells) => table([cells, cells.map(() => "---")]);
const code = (s) => `\`${s}\``;
const en = (pair) => pair?.en ?? "";

mkdirSync(`${ROOT}/docs`, { recursive: true });
mkdirSync(`${ROOT}/ai`, { recursive: true });

/* ── docs/tokens.md ────────────────────────────────────────────────── */

const groups = patterns.groups.map((g) => g.id).concat("print");
const groupTitle = Object.fromEntries(patterns.groups.map((g) => [g.id, g.title.en]));
groupTitle.print = "Print";

const groupNote = Object.fromEntries(patterns.groups.map((g) => [g.id, g.note.en]));
groupNote.print =
  "Reference-only values with no CSS variable. Screen and print surfaces need different coppers, so the two sets are never mixed.";

const tokenSections = groups
  .map((id) => {
    const rows = tokens.filter((t) => t.group === id);
    if (rows.length === 0) return null;
    return [
      `### ${groupTitle[id] ?? id}`,
      "",
      groupNote[id] ?? "",
      "",
      header(["Token", "Value", "Hex", "Use"]),
      table(
        rows.map((t) => [
          t.cssVar ? code(`--${t.name}`) : `${code(t.name)} *`,
          code(t.value),
          t.type === "color" ? toHex(t.value) : "—",
          t.note
            ? `${en(t.use) || t.description}<br>**Note:** ${en(t.note)}`
            : en(t.use) || t.description,
        ]),
      ),
    ].join("\n");
  })
  .filter(Boolean)
  .join("\n\n");

writeFileSync(
  `${ROOT}/docs/tokens.md`,
  `${GENERATED}

# Design tokens

\`@mpc/design\` ${version} · ${tokens.length} tokens (${tokens.filter((t) => t.cssVar).length} CSS variables)

\`tokens/*.json\` is the only source. This document and the CSS, JSON, SCSS, and
Dart in \`dist/\` are all generated from it. \`*\` marks a reference-only value
that produces no CSS variable.

${tokenSections}

## Utility classes

Classes defined by \`dist/utilities.css\`. A ✓ in the **Motion** column means the
\`prefers-reduced-motion\` block disables that class by name.

${header(["Class", "Motion", "Use"])}
${table(
  patterns.utilities.map((u) => [code(`.${u.className}`), u.animated ? "✓" : "", en(u.use)]),
)}
`,
);

/* ── docs/patterns.md ──────────────────────────────────────────────── */

writeFileSync(
  `${ROOT}/docs/patterns.md`,
  `${GENERATED}

# Patterns

Stack-agnostic construction rules. A project that adopts this system inherits
them regardless of framework.

## System rules

${patterns.rules.map((r) => `- **${r.rule.en}**\n  - ${r.why.en}`).join("\n")}

## Component layers

Components fall into six kinds, each bound by one rule. The split holds whatever
UI framework is in use.

${header(["Layer", "Rule"])}
${table(patterns.layers.map((l) => [`**${l.title.en}**`, l.rule.en]))}

## Intent of each token group

${patterns.groups.map((g) => `- **${g.title.en}** — ${g.note.en}`).join("\n")}
`,
);

/* ── docs/voice.md ─────────────────────────────────────────────────── */

writeFileSync(
  `${ROOT}/docs/voice.md`,
  `${GENERATED}

# Voice

These rules are not style preferences. MPC describes a pre-issuance financial
product, and most of what follows exists because the wrong sentence is a
compliance problem, not a bad sentence.

## Positioning

> **${voice.positioning.statement.en}**
>
> ${voice.positioning.expansion.en}

## Claims we do not make

${header(["Not claimed", "Instead"])}
${table(voice.boundaries.map((b) => [`**${b.claim.en}**`, b.instead.en]))}

## Tone rules

${voice.tone
  .map((t) =>
    [`### ${t.rule.en}`, "", t.why.en, t.example ? `\n> Example: ${t.example.en}` : ""].join(
      "\n",
    ),
  )
  .join("\n\n")}

## Bilingual policy

${voice.locale.map((p) => `- **${p.rule.en}**\n  - ${p.why.en}`).join("\n")}
`,
);

/* ── docs/logo.md ──────────────────────────────────────────────────── */

writeFileSync(
  `${ROOT}/docs/logo.md`,
  `${GENERATED}

# Logo

Assets live in \`assets/logo/\`. Use SVG wherever vector scaling is available.
The wordmark is outlined, so it renders without the typeface installed.

## Geometry constraints

${header(["Rule", "Value", "Why"])}
${table(logo.constraints.map((c) => [c.label.en, c.value.en, c.why.en]))}

## Don'ts

${logo.donts.map((d) => `- ${d.en}`).join("\n")}

## Typefaces

${header(["Typeface", "Role", "Weights", "License"])}
${table(logo.typefaces.map((f) => [f.family, f.role.en, f.weights, f.license]))}

All three are open-licensed, so partner and press material can use them without
buying a license.

## Trademark

${logo.trademark.en}

_${logo.trademark.status}_
`,
);

/* ── ai/CLAUDE.md ──────────────────────────────────────────────────── */

/** One line per rule. An agent reads this; it does not need the reasoning. */
const bullets = (items, pick) => items.map((i) => `- ${pick(i)}`).join("\n");

writeFileSync(
  `${ROOT}/ai/CLAUDE.md`,
  `<!-- GENERATED by @mpc/design ${version} scripts/docs.mjs. Regenerate rather than edit. -->

## MPC design system (@mpc/design ${version})

This project follows the MPC design system. The rules below are mandatory.

### Colour and dimensions

- Author every colour as a token. No literal colour values.
- Available CSS variables: ${tokens
    .filter((t) => t.cssVar && t.type === "color")
    .map((t) => `\`--${t.name}\``)
    .join(", ")}
- Radius: ${tokens
    .filter((t) => t.type === "dimension")
    .map((t) => `\`--${t.name}\``)
    .join(", ")}. Never use a larger value.
- Typefaces: ${tokens
    .filter((t) => t.type === "fontFamily")
    .map((t) => `\`--${t.name}\``)
    .join(", ")}.
- Full list and the use of each token: see \`docs/tokens.md\`.

### Construction

${bullets(patterns.rules, (r) => r.rule.en)}

### Component layers

${bullets(patterns.layers, (l) => `**${l.title.en}** — ${l.rule.en}`)}

### Writing copy

Positioning: ${voice.positioning.statement.en}

Claims we do not make:

${bullets(voice.boundaries, (b) => `${b.claim.en} Instead: ${b.instead.en}`)}

Tone:

${bullets(voice.tone, (t) => t.rule.en)}

Bilingual:

${bullets(voice.locale, (p) => p.rule.en)}

### Logo

${bullets(logo.constraints, (c) => `${c.label.en}: ${c.value.en}`)}

Don'ts:

${bullets(logo.donts, (d) => d.en)}
`,
);

console.log(
  `docs/  (tokens.md ${tokens.length} tokens, patterns.md ${patterns.rules.length} rules + ` +
    `${patterns.layers.length} layers, voice.md ${voice.tone.length} tone rules, ` +
    `logo.md ${logo.constraints.length} constraints)\nai/CLAUDE.md`,
);
