/**
 * Copies the generated logo artwork into the package and writes its manifest.
 *
 *   node scripts/sync-assets.mjs   (from the host repo root's design-system/)
 *
 * The artwork generators live in the host repo, not here: they need `sharp`
 * and `opentype.js`, and a design system a Flutter or Figma consumer installs
 * should not drag a native image toolchain along with it. The consequence is
 * deliberate and worth stating — editing the mark means regenerating in the
 * host repo (`bun run build:brand`) and re-running this.
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = resolve(ROOT, "../public/brand");
const OUT = `${ROOT}/assets/logo`;

if (!existsSync(SOURCE)) {
  console.error(
    `No artwork at ${SOURCE}.\n` +
      `Run \`bun run build:brand\` in the host repo first, or point SOURCE at the artwork.`,
  );
  process.exit(1);
}

// Rebuilt from scratch so a renamed or dropped file cannot linger.
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
cpSync(`${SOURCE}/svg`, `${OUT}/svg`, { recursive: true });
cpSync(`${SOURCE}/png`, `${OUT}/png`, { recursive: true });

/** `mpc-lockup-horizontal-on-dark@2x.png` → shape, treatment, scale. */
const describe = (file) => {
  const [, stem, scale] = /^mpc-(.+?)(?:@(\dx))?\.(?:svg|png)$/.exec(file) ?? [];
  if (!stem) return null;

  const treatments = ["mono-black", "mono-white", "on-dark", "on-light"];
  const treatment = treatments.find((t) => stem.endsWith(t));
  if (!treatment) return null;

  return {
    file,
    shape: stem.slice(0, -treatment.length - 1),
    treatment,
    scale: scale ?? "1x",
  };
};

const collect = (dir) =>
  readdirSync(`${OUT}/${dir}`)
    .sort()
    .map((file) => {
      const described = describe(file);
      if (!described) throw new Error(`${dir}/${file}: filename does not match the naming scheme`);
      return {
        ...described,
        path: `assets/logo/${dir}/${file}`,
        bytes: statSync(`${OUT}/${dir}/${file}`).size,
      };
    });

const svg = collect("svg");
const png = collect("png");

writeFileSync(
  `${OUT}/manifest.json`,
  JSON.stringify(
    {
      $description:
        "Logo artwork index. Generated by scripts/sync-assets.mjs from the host repo's build:brand output.",
      shapes: [...new Set(svg.map((a) => a.shape))],
      treatments: [...new Set(svg.map((a) => a.treatment))],
      svg,
      png,
    },
    null,
    2,
  ) + "\n",
);

const kb = (assets) => Math.round(assets.reduce((sum, a) => sum + a.bytes, 0) / 1024);
console.log(`assets/logo/  (${svg.length} SVG ${kb(svg)} KB, ${png.length} PNG ${kb(png)} KB)`);
